-- =========================================================================
-- CrediPulse AI: Supabase Database Schema
-- Run this script in the Supabase SQL Editor (https://supabase.com/dashboard)
-- =========================================================================

-- 1. Create Credit Underwriting Applications Table
CREATE TABLE IF NOT EXISTS public.credit_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    applicant_name TEXT DEFAULT 'Anonymous Applicant',
    person_age INTEGER NOT NULL,
    person_income NUMERIC(12, 2) NOT NULL,
    person_home_ownership TEXT NOT NULL,
    person_emp_length NUMERIC(5, 2) NOT NULL,
    loan_amnt NUMERIC(12, 2) NOT NULL,
    loan_intent TEXT NOT NULL,
    loan_grade TEXT NOT NULL,
    loan_int_rate NUMERIC(6, 2) NOT NULL,
    debt_to_income_ratio NUMERIC(6, 4) NOT NULL,
    revolving_utilization NUMERIC(6, 4) NOT NULL,
    cb_person_cred_hist_length NUMERIC(5, 2) NOT NULL,
    num_open_accounts NUMERIC(5, 2) NOT NULL,
    cb_person_default_on_file TEXT NOT NULL,
    
    -- Machine Learning Predictions
    fico_score INTEGER NOT NULL,
    risk_tier TEXT NOT NULL,
    recommendation TEXT NOT NULL,
    is_default_predicted BOOLEAN NOT NULL,
    consensus_probability NUMERIC(6, 4) NOT NULL,
    model_agreement TEXT,
    
    -- Individual Model Probabilities
    lr_probability NUMERIC(6, 4),
    rf_probability NUMERIC(6, 4),
    gb_probability NUMERIC(6, 4),
    top_risk_factors JSONB
);

-- 2. Create Batch Portfolio Underwriting Jobs Table
CREATE TABLE IF NOT EXISTS public.batch_underwriting_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    total_applicants INTEGER NOT NULL,
    approved_count INTEGER DEFAULT 0,
    rejected_count INTEGER DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    avg_credit_score INTEGER DEFAULT 0,
    approval_rate NUMERIC(6, 2) DEFAULT 0,
    sample_records JSONB
);

-- 3. Create Performance Indexes for Fast Lookups & Sorting
CREATE INDEX IF NOT EXISTS idx_credit_applications_created_at ON public.credit_applications(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_credit_applications_fico ON public.credit_applications(fico_score);
CREATE INDEX IF NOT EXISTS idx_credit_applications_risk_tier ON public.credit_applications(risk_tier);
CREATE INDEX IF NOT EXISTS idx_batch_jobs_created_at ON public.batch_underwriting_jobs(created_at DESC);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.credit_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batch_underwriting_jobs ENABLE ROW LEVEL SECURITY;

-- 5. Create Public Access Policies (Allows API read/write with anon key)
DROP POLICY IF EXISTS "Allow anon select on credit_applications" ON public.credit_applications;
CREATE POLICY "Allow anon select on credit_applications" 
ON public.credit_applications FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow anon insert on credit_applications" ON public.credit_applications;
CREATE POLICY "Allow anon insert on credit_applications" 
ON public.credit_applications FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon select on batch_underwriting_jobs" ON public.batch_underwriting_jobs;
CREATE POLICY "Allow anon select on batch_underwriting_jobs" 
ON public.batch_underwriting_jobs FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Allow anon insert on batch_underwriting_jobs" ON public.batch_underwriting_jobs;
CREATE POLICY "Allow anon insert on batch_underwriting_jobs" 
ON public.batch_underwriting_jobs FOR INSERT TO anon, authenticated WITH CHECK (true);

-- 6. Insert Sample Baseline Decisions
INSERT INTO public.credit_applications (
    applicant_name, person_age, person_income, person_home_ownership, person_emp_length,
    loan_amnt, loan_intent, loan_grade, loan_int_rate, debt_to_income_ratio, revolving_utilization,
    cb_person_cred_hist_length, num_open_accounts, cb_person_default_on_file, fico_score,
    risk_tier, recommendation, is_default_predicted, consensus_probability, model_agreement,
    lr_probability, rf_probability, gb_probability, top_risk_factors
) VALUES 
(
    'Prime Benchmark Applicant', 38, 125000, 'MORTGAGE', 9.0, 15000, 'HOMEIMPROVEMENT', 'A', 6.8, 0.12, 0.18, 14, 11, 'N',
    785, 'Prime (Very Low Risk)', 'Instant Approval (Tier 1 Prime)', false, 0.045, '3 of 3 Models Agree (Consensus)',
    0.052, 0.041, 0.042, '[{"feature": "Revolving Utilization", "impact": "Positive", "detail": "18.0%"}, {"feature": "Debt-to-Income", "impact": "Positive", "detail": "12.0%"}]'::jsonb
),
(
    'Subprime High Risk Sample', 24, 28000, 'RENT', 1.0, 18000, 'DEBTCONSOLIDATION', 'E', 21.5, 0.64, 0.88, 2, 4, 'Y',
    512, 'Deep Subprime (Critical Risk)', 'Decline (High Default Risk)', true, 0.892, '3 of 3 Models Agree (Consensus)',
    0.875, 0.910, 0.891, '[{"feature": "Prior Default on File", "impact": "Negative", "detail": "Yes"}, {"feature": "Debt-to-Income", "impact": "Negative", "detail": "64.0%"}]'::jsonb
);
